### ISSUE TITLE
Warn user when executing "The script will now create an S3 bucket to store data, do you want to continue?" 

### ISSUE THREAD

**Issue by gleeke** [invictus-ir/Invictus-AWS#4]
Maybe allow specifying bucket name, or allow existing bucket to be passed as a command line argument.

**Comment by invictus-ir** [comment]
There are two buckets created and it's done in this section of the code

PREPARATION_BUCKET = 'invictus-aws-'+ date + '-' + random_chars
LOGS_BUCKET = 'invictus-aws-'+ date + '-' + random_chars`

The idea is that we will have information coming out of the enumeration part of the script that will end up in the prep bucket and any logs that are found and extracted will end up in the logs bucket. 
If you want to change this you can simply hardcode a name here for example:


PREPARATION_BUCKET = 'invictus-aws-prep-gleeke1234'
LOGS_BUCKET ='invictus-aws-log-gleeke1234'

We made it like this, because bucket names need to be globally unique which can be quite a challenge, therefore using the current date and add some random characters should be unique enough. But again feel free to change that to your liking.
